### ISSUE TITLE
Support - agent installation error - run the agent as root

### ISSUE THREAD

**Issue by quammy** [syagent/agent-2#17]
Hi,
First time here, trying to install the agent on an Intel NUC running Ubuntu  22.04.1 LTS.

I run the command like this:
```sudo wget -N --no-check-certificate https://raw.githubusercontent.com/syagent/agent-2/main/install.sh && bash install.sh 52.....3a```
but getting the error:
```
Last-modified header missing -- time-stamps turned off.
2023-01-23 13:41:16 (17.0 MB/s) - ‘install.sh’ saved [3521/3521]

|
|   SyAgent Installer
| =
||
| Error: Please run the agent as root
|       The agent will NOT run as root but root required to make the installation success
|
```

Thanks for what seems to be a great tool and service!

**Comment by quammy** [comment]
Just run the code manually - ```sudo bash install.sh 52....3a``` and it worked as expected.

**Comment by Rashe** [comment]
Strange error, I will check the 22.04 installation

**Comment by quammy** [comment]
You can easily replicate on Oracle free (for life) cloud server - choose the Ubuntu image. Happened now 2 times in a row on that server while worked as expected on an Ubuntu 22.04.1 LTS that is installed on another machine in my home.

**Comment by Rashe** [comment]
As I understood you logged in as Ubuntu user and tried to install the agent. And then you did `sudo su` to install the agent?

**Comment by quammy** [comment]
maybe at first yes, but on other machines I tried immediately with sudo with the same results.

**Comment by Rashe** [comment]
Yes, but you need to be root user when you install the agent. That's why you use `sudo su`

**Comment by quammy** [comment]
so maybe this will work?

sudo wget -N --no-check-certificate https://raw.githubusercontent.com/syagent/agent-2/main/install.sh && **_sudo_** bash install.sh 52.....3a

**Comment by quammy** [comment]
> sudo wget -N --no-check-certificate https://raw.githubusercontent.com/syagent/agent-2/main/install.sh && **_sudo_** bash install.sh 52.....3a

yep, that worked 100%.
