### ISSUE TITLE
Bug - text changes on all alerts instead of not at all or maybe only on latest

### ISSUE THREAD

**Issue by quammy** [syagent/agent-2#23]
As described on the subject. Here is a print screen with details:
![image](https://user-images.githubusercontent.com/3137488/218775851-2af162dd-0748-46a7-93be-77eb5e587cfc.png)

**Comment by Rashe** [comment]
It's not a bug, the message of "last fetched" is when actually the last data was received, so if agent started getting data again, you will see this :)

**Comment by quammy** [comment]
Thanks for clearing out the feature;)
But this design prevents the user from tracking what really happened. For example, for how long was the outage during the last alert, the one before it and so on. This is an important piece of information, IMHO.

**Comment by Rashe** [comment]
You are right
