### ISSUE TITLE
unable to disable CPU is high for 6 minutes

### ISSUE THREAD

**Issue by t0mZ4** [syagent/agent-2#29]
no option to disable this alarm

![image](https://github.com/syagent/agent-2/assets/31729091/75f7dd7c-e75b-4b66-87e0-d363f721a982)

**Comment by Rashe** [comment]
It should be CPU usage 100%. it doesn't work?

**Comment by t0mZ4** [comment]
hi, doesn't!

![image](https://github.com/syagent/agent-2/assets/31729091/80e183c7-5136-420b-afa9-bc9c43061e6e)

![image](https://github.com/syagent/agent-2/assets/31729091/827fc130-85c8-476b-9344-4dff6bd185a1)

**Comment by Rashe** [comment]
It was my bad, thx for report. It's fixed.
