### ISSUE TITLE
[bug] Error in sending data

### ISSUE THREAD

**Issue by Penton7** [syagent/agent-2#31]
On one of my servers, a service stopped working. After several attempts I found the problem.
It was related to a large size in the multipart_data variable.

 The error is called in the file sh-agent.sh line 179
![image](https://github.com/syagent/agent-2/assets/47526333/6cd91255-5ac4-4ac2-8c12-d89573bd0704)

If you add the output of the variable to the script, it looks like this:
![image](https://github.com/syagent/agent-2/assets/47526333/46622250-d99a-4d9d-966c-cc48eeb220d8)

**Comment by Rashe** [comment]
Hi, thx for report

I will take a look, do you have many discs on your server? or processes? I just try to figure out what is it so large? 

Anyway I will increase the payload.

**Comment by Penton7** [comment]
> Hi, thx for report
> 
> I will take a look, do you have many discs on your server? or processes? I just try to figure out what is it so large?
> 
> Anyway I will increase the payload.

yes, I have a lot of processes on my server :)
![image](https://github.com/syagent/agent-2/assets/47526333/170feb23-eb54-4a0d-ba8a-90fee8919251)

**Comment by Rashe** [comment]
I increased the payload size also
