### ISSUE TITLE
adding syagent to the firewall

### ISSUE THREAD

**Issue by t0mZ4** [syagent/agent-2#6]
Hi

in some cases I limit outgoing traffic from the servers, and I'd like to white-list syagent servers and ports

can you tell me what they are?

**Comment by Rashe** [comment]
Hey Tom.
It's regular http post request to https://agent.syagent.com/agent​.

Tell me if it helped.

**Comment by t0mZ4** [comment]
yeap that works

**Comment by t0mZ4** [comment]
yeap that works, i created a rule to permit https traffic to agent.syagent.com

**Comment by t0mZ4** [comment]
hi, are you sure this is the only hostname that the agent communicates with? Since I enable the BLOCK ALL TRAFFIC and enabled HTTPS traffic only, or now even ENABLE ALL TRAFFIC to agent.syagent.com

I get the following alarm often: Agent stopped receiving data

**Comment by Rashe** [comment]
> hi, are you sure this is the only hostname that the agent communicates with? Since I enable the BLOCK ALL TRAFFIC and enabled HTTPS traffic only, or now even ENABLE ALL TRAFFIC to agent.syagent.com
> 
> I get the following alarm often: Agent stopped receiving data

Hi, yes :)

The only thing agent calls is "agent.syagent.com"

**Comment by Rashe** [comment]
Hey @t0mZ4 , did you solve the firewall problem?

**Comment by t0mZ4** [comment]
Hi, actually no,
![image](https://user-images.githubusercontent.com/31729091/163256675-41d72892-3eb5-479c-8848-572520b195e3.png)


but in a day or two, i can finally disable this BLOCK ALL rule on this server, and i will be able to determine if indeed it is a BLOCK rule that is causing it, or something else in the server connectivity.
