### ISSUE TITLE
RAM Spikes graphs are displaying wrong data

### ISSUE THREAD

**Issue by t0mZ4** [syagent/agent-2#7]
Hi
there are issues in the RAM Spikes graphs

this server for example has 16gb of ram but it showing much greater numbers. The Y-Axis values are clipping because of that as well

![image](https://user-images.githubusercontent.com/31729091/164959302-213f22cd-6970-4378-9ede-ad03dedb3dc8.png)

**Comment by Rashe** [comment]
Thanks, I will fix it

**Comment by Rashe** [comment]
Holidays, means I have some time to fix things :D
