### ISSUE TITLE
[feature request] add ability to re-arrange server order in Card view

### ISSUE THREAD

**Issue by t0mZ4** [syagent/agent-2#9]
It can be nice to have option to re-arrange server cards, I'd like to have my most important servers first on the left

notice that I wrote Card View, which is the only view currently. 
It can be nice in the future to add a table view as well and have even more sorting abilities there, like sort by alert count, sort by cpu usage.

what do you think?

**Comment by t0mZ4** [comment]
on that note, i would suggest taking an Editable Dashboard approach where dashboard widgets can be re-arranged/add/removed

the sooner you implement this type of framework in the UI =)

**Comment by Rashe** [comment]
Hey Tom, I added filter. 

I will add table view a bit later
